CREATE TABLE IF NOT EXISTS item (
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         description VARCHAR NOT NULL,
                         created VARCHAR NOT NULL,
                         done boolean NOT NULL
);